# Generated by Django 3.1 on 2021-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='todo',
            name='categories',
            field=models.ManyToManyField(to='todos.Category'),
        ),
    ]
