# Generated by Django 3.1 on 2021-06-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20210609_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
